/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_math_Cuda_upool2D */

#ifndef _Included_z_dragon_engine_cuda_impl_math_Cuda_upool2D
#define _Included_z_dragon_engine_cuda_impl_math_Cuda_upool2D
#ifdef __cplusplus
extern "C" {
#endif
#undef z_dragon_engine_cuda_impl_math_Cuda_upool2D_LIKE_CONV3D
#define z_dragon_engine_cuda_impl_math_Cuda_upool2D_LIKE_CONV3D 1L
	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_upool2D
	 * Method:    upool2D_max
	 * Signature: ([JIJJIIIIJJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1upool2D_upool2D_1max
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jint, jint, jint, jint, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_upool2D
	 * Method:    upool2D_max_Indexed
	 * Signature: ([JIJJIIIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1upool2D_upool2D_1max_1Indexed
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_upool2D
	 * Method:    upool2D_avg
	 * Signature: ([JIJIIIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1upool2D_upool2D_1avg
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_upool2D
	 * Method:    upool2D_avg_tiled
	 * Signature: ([JIJIIIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1upool2D_upool2D_1avg_1tiled
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_upool2D
	 * Method:    upool2D_avg_ignore_padding
	 * Signature: ([JIJIIIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1upool2D_upool2D_1avg_1ignore_1padding
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_upool2D
	 * Method:    upool2D_avg_ignore_padding_tiled
	 * Signature: ([JIJIIIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1upool2D_upool2D_1avg_1ignore_1padding_1tiled
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
