/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_math_Cuda_pool2D */

#ifndef _Included_z_dragon_engine_cuda_impl_math_Cuda_pool2D
#define _Included_z_dragon_engine_cuda_impl_math_Cuda_pool2D
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_pool2D
	 * Method:    pool2D_max
	 * Signature: ([JIJIIIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1pool2D_pool2D_1max
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_pool2D
	 * Method:    pool2D_max_indexed
	 * Signature: ([JIJIIIIJJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1pool2D_pool2D_1max_1indexed
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jint, jint, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_pool2D
	 * Method:    pool2D_avg
	 * Signature: ([JIJIIIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1pool2D_pool2D_1avg
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_pool2D
	 * Method:    pool2D_avg_ignore_padding
	 * Signature: ([JIJIIIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1pool2D_pool2D_1avg_1ignore_1padding
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
