/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_math_Cuda_matMul */

#ifndef _Included_z_dragon_engine_cuda_impl_math_Cuda_matMul
#define _Included_z_dragon_engine_cuda_impl_math_Cuda_matMul
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_matMul
	 * Method:    SKbuf_summary
	 * Signature: (JJJII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1matMul_SKbuf_1summary
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_matMul
	 * Method:    matMul_K2pow
	 * Signature: ([JIJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1matMul_matMul_1K2pow
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_matMul
	 * Method:    matMul
	 * Signature: ([JIJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1matMul_matMul
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_matMul
	 * Method:    matMulT1_MGK
	 * Signature: ([JIJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1matMul_matMulT1_1MGK
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_matMul
	 * Method:    matMulT1
	 * Signature: ([JIJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1matMul_matMulT1
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_matMul
	 * Method:    matMulT1SK
	 * Signature: ([JIIJJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1matMul_matMulT1SK
	(JNIEnv *, jclass, jlongArray, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_matMul
	 * Method:    matMulT2_K2pow
	 * Signature: ([JIJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1matMul_matMulT2_1K2pow
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_matMul
	 * Method:    matMulT2
	 * Signature: ([JIJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1matMul_matMulT2
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
