/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_math_Cuda_function */

#ifndef _Included_z_dragon_engine_cuda_impl_math_Cuda_function
#define _Included_z_dragon_engine_cuda_impl_math_Cuda_function
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    equal_abs2D
	 * Signature: (JJJFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_equal_1abs2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    equal_abs2D_char
	 * Signature: (JJJBBJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_equal_1abs2D_1char
	(JNIEnv *, jclass, jlong, jlong, jlong, jbyte, jbyte, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    equal_abs2D_int
	 * Signature: (JJJIIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_equal_1abs2D_1int
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear_greater2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear_1greater2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear_greater_dual2D
	 * Signature: (JJJFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear_1greater_1dual2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear_dual_out2D
	 * Signature: (JJFFFFJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear_1dual_1out2D
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear2D_char2float
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear2D_1char2float
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear2D_float2char
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear2D_1float2char
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear2D_int2float
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear2D_1int2float
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear2D_float2int
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear2D_1float2int
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear_dual2D
	 * Signature: (JJJFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear_1dual2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear_dual2D_row
	 * Signature: (JJJIFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear_1dual2D_1row
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    linear_dual2D_field
	 * Signature: (JJJIFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_linear_1dual2D_1field
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    quadratic2D
	 * Signature: (JJFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_quadratic2D
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    quadratic2D_deltaX
	 * Signature: (JJJJFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_quadratic2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    quadratic_dual2D
	 * Signature: (JJJFFFFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_quadratic_1dual2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    quadratic_dual2D_deltaX
	 * Signature: (JJJJJJFFFFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_quadratic_1dual2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    quadratic_dual2D_row
	 * Signature: (JJJIFFFFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_quadratic_1dual2D_1row
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    quadratic_dual2D_field
	 * Signature: (JJJIFFFFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_quadratic_1dual2D_1field
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    variance2D_f64
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_variance2D_1f64
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    rpl2D
	 * Signature: (JFJFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_rpl2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    rpl2D_deltaX
	 * Signature: (JJJJFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_rpl2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    div2D
	 * Signature: (JFJFFJFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_div2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    div2D_deltaX
	 * Signature: (JJJJJFFJFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_div2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    div2D_row
	 * Signature: (JFJFFJFFIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_div2D_1row
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    div2D_field
	 * Signature: (JFJFFJFFIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_div2D_1field
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    add_div2D_row
	 * Signature: (JJJJIFFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_add_1div2D_1row
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jfloat, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    add_div2D_field
	 * Signature: (JJJJIFFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_add_1div2D_1field
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jfloat, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sign2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sign2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    ceil2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_ceil2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    floor2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_floor2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    abs2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_abs2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    abs2D_deltaX
	 * Signature: (JJJJFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_abs2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    zero_nan2D
	 * Signature: (JJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_zero_1nan2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sqrt2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sqrt2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sqrt_quadratic_dual2D
	 * Signature: (JJJFFFFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sqrt_1quadratic_1dual2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    min2D
	 * Signature: (JFJFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_min2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    min_dual2D
	 * Signature: (JFJFFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_min_1dual2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    max2D
	 * Signature: (JFJFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_max2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    max_dual2D
	 * Signature: (JFJFFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_max_1dual2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    clip2D
	 * Signature: (JFJFFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_clip2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    exp2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_exp2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    log2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_log2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    log2D_deltaX
	 * Signature: (JJJJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_log2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    relu2D
	 * Signature: (JJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_relu2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    relu2D_deltaX_v1
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_relu2D_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    relu2D_deltaX_v2
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_relu2D_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    leakyRelu2D
	 * Signature: (JJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_leakyRelu2D
	(JNIEnv *, jclass, jlong, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    leakyRelu2D_deltaX_v1
	 * Signature: (JJJJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_leakyRelu2D_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    leakyRelu2D_deltaX_v2
	 * Signature: (JJJJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_leakyRelu2D_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    elu2D
	 * Signature: (JJFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_elu2D
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    elu2D_deltaX_v1
	 * Signature: (JJJJFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_elu2D_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    elu2D_deltaX_v2
	 * Signature: (JJJJFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_elu2D_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    softPlus2D
	 * Signature: (JJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_softPlus2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    softPlus2D_deltaX_v1
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_softPlus2D_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    softPlus2D_deltaX_v2
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_softPlus2D_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    tanh2D
	 * Signature: (JJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_tanh2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    tanh2D_deltaX_v1
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_tanh2D_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    tanh2D_deltaX_v2
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_tanh2D_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sigmoid2D
	 * Signature: (JJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sigmoid2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sigmoid2D_deltaX_v1
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sigmoid2D_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sigmoid2D_deltaX_v2
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sigmoid2D_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    softmax2D_deltaX
	 * Signature: (JJJJJIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_softmax2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    logsoftmax2D
	 * Signature: (JJJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_logsoftmax2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    logsoftmax2D_deltaX
	 * Signature: (JJJJJIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_logsoftmax2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sin2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sin2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sin2D_deltaX
	 * Signature: (JJJJFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sin2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    tan2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_tan2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    tan2D_deltaX
	 * Signature: (JJJJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_tan2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    halfSin2D
	 * Signature: (JFFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_halfSin2D
	(JNIEnv *, jclass, jlong, jfloat, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    halfSin2D_deltaX
	 * Signature: (JJJJFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_halfSin2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    arcsin2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_arcsin2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    arcsin2D_deltaX
	 * Signature: (JJJJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_arcsin2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    arctan2D
	 * Signature: (JFJFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_arctan2D
	(JNIEnv *, jclass, jlong, jfloat, jlong, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    arctan2D_deltaX
	 * Signature: (JJJJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_arctan2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    L1_2D
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_L1_12D
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    L1_2D_deltaYh
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_L1_12D_1deltaYh
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    L2_2D
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_L2_12D
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    L2_2D_deltaYh
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_L2_12D_1deltaYh
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    smoothL1_2D
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_smoothL1_12D
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    smoothL1_2D_deltaYh
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_smoothL1_12D_1deltaYh
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    binaryCrossEntropy2D
	 * Signature: (JJJFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_binaryCrossEntropy2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    binaryCrossEntropy2D_deltaYh
	 * Signature: (JJJFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_binaryCrossEntropy2D_1deltaYh
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sigmoid_binaryCrossEntropy2D
	 * Signature: (JJJFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sigmoid_1binaryCrossEntropy2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sigmoid_binaryCrossEntropy2D_deltaX
	 * Signature: (JJJFFJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sigmoid_1binaryCrossEntropy2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    crossEntropy2D
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_crossEntropy2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    crossEntropy2D_deltaYh
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_crossEntropy2D_1deltaYh
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    softmax_crossEntropy2D
	 * Signature: (JJJJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_softmax_1crossEntropy2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    softmax_crossEntropy2D_deltaX
	 * Signature: (JJJJJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_softmax_1crossEntropy2D_1deltaX
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    momentum2D
	 * Signature: (JJJFFJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_momentum2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    momentum2D_decay
	 * Signature: (JJJFFJFFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_momentum2D_1decay
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sgdmn2D
	 * Signature: (JJJFFFJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sgdmn2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sgdmn2D_decay
	 * Signature: (JJJFFFJFFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sgdmn2D_1decay
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    rmsprop2D
	 * Signature: (JJJFFFJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_rmsprop2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    rmsprop2D_decay
	 * Signature: (JJJFFFJFFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_rmsprop2D_1decay
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    adam2D
	 * Signature: (JJJFFJFFFJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_adam2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    adam2D_type2
	 * Signature: (JJJFFFJFFFFJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_adam2D_1type2
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jfloat, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    adam2D_decay
	 * Signature: (JJJFFJFFFJFFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_adam2D_1decay
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    adamax2D
	 * Signature: (JJJFFJFFJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_adamax2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    adamax2D_decay
	 * Signature: (JJJFFJFFJFFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_adamax2D_1decay
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    adamW2D
	 * Signature: (JJJFFJFFFJFFFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_adamW2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    adamod2D
	 * Signature: (JJJFFJFFFJFFJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_adamod2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jlong, jfloat, jfloat, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    adamod2D_decay
	 * Signature: (JJJFFJFFFJFFJFFFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_adamod2D_1decay
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jlong, jfloat, jfloat, jlong, jfloat, jfloat, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    affine2D_row
	 * Signature: (JJJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_affine2D_1row
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sqBatchNorm2D_row
	 * Signature: (JJJJFIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sqBatchNorm2D_1row
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sqBatchNorm_affined2D_row
	 * Signature: (JJJJFJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sqBatchNorm_1affined2D_1row
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sqBatchNorm2D_row_deltaX_v1
	 * Signature: (JJJJJFJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sqBatchNorm2D_1row_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sqBatchNorm2D_row_deltaX_v2
	 * Signature: (JJJJJFJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sqBatchNorm2D_1row_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sqBatchNorm_affined2D_row_deltaX_v1
	 * Signature: (JJJJJFJJJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sqBatchNorm_1affined2D_1row_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    sqBatchNorm_affined2D_row_deltaX_v2
	 * Signature: (JJJJJFJJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_sqBatchNorm_1affined2D_1row_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    batchNorm2D_row
	 * Signature: (JJJJFIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_batchNorm2D_1row
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    batchNorm_affined2D_row
	 * Signature: (JJJJFJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_batchNorm_1affined2D_1row
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    batchNorm2D_row_deltaX_v1
	 * Signature: (JJJJFJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_batchNorm2D_1row_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    batchNorm2D_row_deltaX_v2
	 * Signature: (JJJJJFJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_batchNorm2D_1row_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    batchNorm_affined2D_row_deltaX_v1
	 * Signature: (JJJJFJJJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_batchNorm_1affined2D_1row_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    batchNorm_affined2D_row_deltaX_v2
	 * Signature: (JJJJJFJJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_batchNorm_1affined2D_1row_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    layerNorm2D_row
	 * Signature: (JJJJFIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_layerNorm2D_1row
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    layerNorm2D_row_deltaX_v1
	 * Signature: (JJJJJFJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_layerNorm2D_1row_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    layerNorm2D_row_deltaX_v2
	 * Signature: (JJJJJFJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_layerNorm2D_1row_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    layerNorm_affined2D_row
	 * Signature: (JJJJFJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_layerNorm_1affined2D_1row
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    layerNorm_affined2D_row_deltaX_v1
	 * Signature: (JJJJJFJJJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_layerNorm_1affined2D_1row_1deltaX_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    layerNorm_affined2D_row_deltaX_v2
	 * Signature: (JJJJJFJJJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_layerNorm_1affined2D_1row_1deltaX_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    onehot2D_row_int
	 * Signature: (JJFFIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_onehot2D_1row_1int
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    onehot2D_row_char
	 * Signature: (JJFFIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_onehot2D_1row_1char
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_function
	 * Method:    pix2tensor2D
	 * Signature: (JJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1function_pix2tensor2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
