/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_math_Cuda_batchMatMul */

#ifndef _Included_z_dragon_engine_cuda_impl_math_Cuda_batchMatMul
#define _Included_z_dragon_engine_cuda_impl_math_Cuda_batchMatMul
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_batchMatMul
	 * Method:    batchMatMul
	 * Signature: ([JIJJJIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1batchMatMul_batchMatMul
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_batchMatMul
	 * Method:    batchMatMul_texture
	 * Signature: ([JIJJJIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1batchMatMul_batchMatMul_1texture
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_batchMatMul
	 * Method:    batchMatMulT1
	 * Signature: ([JIJJJIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1batchMatMul_batchMatMulT1
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_batchMatMul
	 * Method:    batchMatMulT2
	 * Signature: ([JIJJJIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1batchMatMul_batchMatMulT2
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_batchMatMul
	 * Method:    batchMatMulT2_texture
	 * Signature: ([JIJJJIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1batchMatMul_batchMatMulT2_1texture
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
