/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW */

#ifndef _Included_z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW
#define _Included_z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW
#ifdef __cplusplus
extern "C" {
#endif
#undef z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW_IM2COL_GEMM
#define z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW_IM2COL_GEMM 1L
	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW
	 * Method:    dconv3D_deltaW
	 * Signature: ([JIJIIJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaW_dconv3D_1deltaW
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW
	 * Method:    dconv3D_deltaW_W1
	 * Signature: ([JIJIIJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaW_dconv3D_1deltaW_1W1
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW
	 * Method:    buf_summary
	 * Signature: (JJJII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaW_buf_1summary
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW
	 * Method:    dconv3D_deltaW_GemmSK
	 * Signature: ([JIIJIIJIIJJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaW_dconv3D_1deltaW_1GemmSK
	(JNIEnv *, jclass, jlongArray, jint, jint, jlong, jint, jint, jlong, jint, jint, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW
	 * Method:    dconv3D_deltaW_GemmV2SK
	 * Signature: ([JIIJIIJIIJJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaW_dconv3D_1deltaW_1GemmV2SK
	(JNIEnv *, jclass, jlongArray, jint, jint, jlong, jint, jint, jlong, jint, jint, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaW
	 * Method:    dconv3D_deltaW_GemmSK_W1
	 * Signature: ([JIIJIIJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaW_dconv3D_1deltaW_1GemmSK_1W1
	(JNIEnv *, jclass, jlongArray, jint, jint, jlong, jint, jint, jlong, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
