#pragma once

/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class z_dragon_engine_cuda_impl_CudaDevice */

#ifndef _Included_z_dragon_engine_cuda_impl_CudaDevice
#define _Included_z_dragon_engine_cuda_impl_CudaDevice
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     z_dragon_engine_cuda_impl_CudaDevice
	 * Method:    setProperty
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_CudaDevice_setProperty
	(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
