/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_Cuda */

#ifndef _Included_z_dragon_engine_cuda_impl_Cuda
#define _Included_z_dragon_engine_cuda_impl_Cuda
#ifdef __cplusplus
extern "C" {
#endif
#undef z_dragon_engine_cuda_impl_Cuda_memcpyHostToDevice
#define z_dragon_engine_cuda_impl_Cuda_memcpyHostToDevice 0L
#undef z_dragon_engine_cuda_impl_Cuda_memcpyHostToHost
#define z_dragon_engine_cuda_impl_Cuda_memcpyHostToHost 1L
#undef z_dragon_engine_cuda_impl_Cuda_memcpyDeviceToHost
#define z_dragon_engine_cuda_impl_Cuda_memcpyDeviceToHost 2L
#undef z_dragon_engine_cuda_impl_Cuda_memcpyDeviceToDevice
#define z_dragon_engine_cuda_impl_Cuda_memcpyDeviceToDevice 3L
#undef z_dragon_engine_cuda_impl_Cuda_memcpyDefault
#define z_dragon_engine_cuda_impl_Cuda_memcpyDefault 4L
#undef z_dragon_engine_cuda_impl_Cuda_cudaStreamBlocking
#define z_dragon_engine_cuda_impl_Cuda_cudaStreamBlocking 0L
#undef z_dragon_engine_cuda_impl_Cuda_cudaStreamNonBlocking
#define z_dragon_engine_cuda_impl_Cuda_cudaStreamNonBlocking 1L
	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    malloc
	 * Signature: (J)J
	 */
	JNIEXPORT jlong JNICALL Java_z_dragon_engine_cuda_impl_Cuda_malloc
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    free
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_free
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    mallocHost
	 * Signature: (J)J
	 */
	JNIEXPORT jlong JNICALL Java_z_dragon_engine_cuda_impl_Cuda_mallocHost
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    freeHost
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_freeHost
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    memsetAsync
	 * Signature: (JJIJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_memsetAsync
	(JNIEnv *, jclass, jlong, jlong, jint, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    memcpyAsyncHostToDevice
	 * Signature: (JJJJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_memcpyAsyncHostToDevice
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    memcpyAsyncHostToHost
	 * Signature: (JJJJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_memcpyAsyncHostToHost
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    memcpyAsyncDeviceToHost
	 * Signature: (JJJJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_memcpyAsyncDeviceToHost
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    memcpyAsyncDeviceToDevice
	 * Signature: (JJJJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_memcpyAsyncDeviceToDevice
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    memcpyAsyncDefault
	 * Signature: (JJJJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_memcpyAsyncDefault
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    getDeviceId
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_Cuda_getDeviceId
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    getDeviceCount
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_Cuda_getDeviceCount
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    setDevice
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_setDevice
	(JNIEnv *, jclass, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    resetDevice
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_resetDevice
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    deviceSynchronize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_deviceSynchronize
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    isDeviceP2PAccessEnabled
	 * Signature: (II)Z
	 */
	JNIEXPORT jboolean JNICALL Java_z_dragon_engine_cuda_impl_Cuda_isDeviceP2PAccessEnabled
	(JNIEnv *, jclass, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    enableDeviceP2PAccess
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_enableDeviceP2PAccess
	(JNIEnv *, jclass, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    disableDeviceP2PAccess
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_disableDeviceP2PAccess
	(JNIEnv *, jclass, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    getStreamPriorityRange
	 * Signature: ()[I
	 */
	JNIEXPORT jintArray JNICALL Java_z_dragon_engine_cuda_impl_Cuda_getStreamPriorityRange
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    newStream_Blocking
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_z_dragon_engine_cuda_impl_Cuda_newStream_1Blocking__
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    newStream_Blocking
	 * Signature: (I)J
	 */
	JNIEXPORT jlong JNICALL Java_z_dragon_engine_cuda_impl_Cuda_newStream_1Blocking__I
	(JNIEnv *, jclass, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    newStream_NonBlocking
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_z_dragon_engine_cuda_impl_Cuda_newStream_1NonBlocking__
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    newStream_NonBlocking
	 * Signature: (I)J
	 */
	JNIEXPORT jlong JNICALL Java_z_dragon_engine_cuda_impl_Cuda_newStream_1NonBlocking__I
	(JNIEnv *, jclass, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    deleteStream
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_deleteStream__J
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    deleteStream
	 * Signature: ([JI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_deleteStream___3JI
	(JNIEnv *, jclass, jlongArray, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    streamQuery
	 * Signature: (J)Z
	 */
	JNIEXPORT jboolean JNICALL Java_z_dragon_engine_cuda_impl_Cuda_streamQuery
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    streamSynchronize
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_streamSynchronize__J
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    streamSynchronize
	 * Signature: ([JI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_streamSynchronize___3JI
	(JNIEnv *, jclass, jlongArray, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    newEvent_Default
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_z_dragon_engine_cuda_impl_Cuda_newEvent_1Default
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    newEvent_BlockingSync
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_z_dragon_engine_cuda_impl_Cuda_newEvent_1BlockingSync
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    newEvent_DisableTiming
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_z_dragon_engine_cuda_impl_Cuda_newEvent_1DisableTiming
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    newEvent_Interprocess
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_z_dragon_engine_cuda_impl_Cuda_newEvent_1Interprocess
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    deleteEvent
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_deleteEvent
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    eventRecord
	 * Signature: (JJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_eventRecord__JJ
	(JNIEnv *, jclass, jlong, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    eventRecord
	 * Signature: (J[JI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_eventRecord__J_3JI
	(JNIEnv *, jclass, jlong, jlongArray, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    eventSynchronize
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_eventSynchronize
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    eventElapsedTime
	 * Signature: (JJ)F
	 */
	JNIEXPORT jfloat JNICALL Java_z_dragon_engine_cuda_impl_Cuda_eventElapsedTime
	(JNIEnv *, jclass, jlong, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    streamWaitEvent_default
	 * Signature: (JJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_streamWaitEvent_1default
	(JNIEnv *, jclass, jlong, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    streamWaitEvent_external
	 * Signature: (JJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_streamWaitEvent_1external
	(JNIEnv *, jclass, jlong, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    streamsWaitEvent_default
	 * Signature: ([JIJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_streamsWaitEvent_1default
	(JNIEnv *, jclass, jlongArray, jint, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    streamsWaitEvent_external
	 * Signature: ([JIJ)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_streamsWaitEvent_1external
	(JNIEnv *, jclass, jlongArray, jint, jlong);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    getExceptionName
	 * Signature: (I)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_z_dragon_engine_cuda_impl_Cuda_getExceptionName
	(JNIEnv *, jclass, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    getExceptionInfo
	 * Signature: (I)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_z_dragon_engine_cuda_impl_Cuda_getExceptionInfo
	(JNIEnv *, jclass, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    getLastExceptionType
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_Cuda_getLastExceptionType
	(JNIEnv *, jclass);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get1D
	 * Signature: (JJ[FI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get1D
	(JNIEnv *, jclass, jlong, jlong, jfloatArray, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get2D
	 * Signature: (JJ[FIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get2D
	(JNIEnv *, jclass, jlong, jlong, jfloatArray, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get1D_v2
	 * Signature: (JJ[FJI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get1D_1v2
	(JNIEnv *, jclass, jlong, jlong, jfloatArray, jlong, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get2D_v2
	 * Signature: (JJ[FJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get2D_1v2
	(JNIEnv *, jclass, jlong, jlong, jfloatArray, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set1D
	 * Signature: (JJFI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set1D__JJFI
	(JNIEnv *, jclass, jlong, jlong, jfloat, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set2D
	 * Signature: (JJFIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set2D__JJFIII
	(JNIEnv *, jclass, jlong, jlong, jfloat, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set1D
	 * Signature: (JJ[BI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set1D__JJ_3BI
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set1D
	 * Signature: (JJ[FI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set1D__JJ_3FI
	(JNIEnv *, jclass, jlong, jlong, jfloatArray, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set1D_v2
	 * Signature: (JJ[BJI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set1D_1v2__JJ_3BJI
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set1D_v2
	 * Signature: (JJ[FJI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set1D_1v2__JJ_3FJI
	(JNIEnv *, jclass, jlong, jlong, jfloatArray, jlong, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set2D
	 * Signature: (JJ[BIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set2D__JJ_3BIII
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set2D
	 * Signature: (JJ[FIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set2D__JJ_3FIII
	(JNIEnv *, jclass, jlong, jlong, jfloatArray, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set2D_v2
	 * Signature: (JJ[BJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set2D_1v2__JJ_3BJIII
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set2D_v2
	 * Signature: (JJ[FJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set2D_1v2__JJ_3FJIII
	(JNIEnv *, jclass, jlong, jlong, jfloatArray, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    setFrom1Dto2D
	 * Signature: (JJIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_setFrom1Dto2D
	(JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    setFrom2Dto1D
	 * Signature: (JJIIIJI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_setFrom2Dto1D
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jlong, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    setFrom2Dto2D
	 * Signature: (JJIIIJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_setFrom2Dto2D
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get1D_int
	 * Signature: (JJ[II)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get1D_1int
	(JNIEnv *, jclass, jlong, jlong, jintArray, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get2D_int
	 * Signature: (JJ[IIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get2D_1int
	(JNIEnv *, jclass, jlong, jlong, jintArray, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get1D_v2_int
	 * Signature: (JJ[IJI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get1D_1v2_1int
	(JNIEnv *, jclass, jlong, jlong, jintArray, jlong, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get2D_v2_int
	 * Signature: (JJ[IJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get2D_1v2_1int
	(JNIEnv *, jclass, jlong, jlong, jintArray, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set1D_int
	 * Signature: (JJ[II)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set1D_1int
	(JNIEnv *, jclass, jlong, jlong, jintArray, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set2D_int
	 * Signature: (JJ[IIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set2D_1int
	(JNIEnv *, jclass, jlong, jlong, jintArray, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set1D_v2_int
	 * Signature: (JJ[IJI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set1D_1v2_1int
	(JNIEnv *, jclass, jlong, jlong, jintArray, jlong, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set2D_v2_int
	 * Signature: (JJ[IJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set2D_1v2_1int
	(JNIEnv *, jclass, jlong, jlong, jintArray, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get1D_char
	 * Signature: (JJ[BI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get1D_1char
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get2D_char
	 * Signature: (JJ[BIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get2D_1char
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get1D_v2_char
	 * Signature: (JJ[BJI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get1D_1v2_1char
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    get2D_v2_char
	 * Signature: (JJ[BJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_get2D_1v2_1char
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set1D_char
	 * Signature: (JJ[BI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set1D_1char
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set2D_char
	 * Signature: (JJ[BIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set2D_1char
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set1D_v2_char
	 * Signature: (JJ[BJI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set1D_1v2_1char
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set2D_v2_char
	 * Signature: (JJ[BJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set2D_1v2_1char
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda
	 * Method:    set2D_v2_char_W3S4
	 * Signature: (JJ[BJJI)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_set2D_1v2_1char_1W3S4
	(JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
