/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_math_Cuda_reduce */

#ifndef _Included_z_dragon_engine_cuda_impl_math_Cuda_reduce
#define _Included_z_dragon_engine_cuda_impl_math_Cuda_reduce
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    straight_linear
	 * Signature: (JJFFIJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_straight_1linear
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    straight_quadratic
	 * Signature: (JJFFFIJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_straight_1quadratic
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jfloat, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    straight_max
	 * Signature: (JJIJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_straight_1max
	(JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    straight_min
	 * Signature: (JJIJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_straight_1min
	(JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    straight_max_indexed
	 * Signature: (JJIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_straight_1max_1indexed
	(JNIEnv *, jclass, jlong, jlong, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    straight_min_indexed
	 * Signature: (JJIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_straight_1min_1indexed
	(JNIEnv *, jclass, jlong, jlong, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_linear
	 * Signature: (JJFFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1linear
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_linear_dual
	 * Signature: (JJJFFFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1linear_1dual
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_quadratic
	 * Signature: (JJFFFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1quadratic
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_quadratic_dual
	 * Signature: (JJJFFFFFFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1quadratic_1dual
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_linear_quadratic
	 * Signature: (JJJFFFFFIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1linear_1quadratic
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_max
	 * Signature: (JJIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1max
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_min
	 * Signature: (JJIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1min
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_max_indexed
	 * Signature: (JJIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1max_1indexed
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_min_indexed
	 * Signature: (JJIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1min_1indexed
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_affine_deltaA_v1
	 * Signature: (JJJJJIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1affine_1deltaA_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_affine_deltaAB_v1
	 * Signature: (JJJJJJIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1affine_1deltaAB_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_affine_deltaAB_v2
	 * Signature: (JJJJIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1affine_1deltaAB_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_sqBatchNorm_deltaA_v2
	 * Signature: (JJJJJFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1sqBatchNorm_1deltaA_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_sqBatchNorm_deltaAB_v2
	 * Signature: (JJJJJJFIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1sqBatchNorm_1deltaAB_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jfloat, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_batchNorm_deltaA_v2
	 * Signature: (JJJJJFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1batchNorm_1deltaA_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_batchNorm_deltaAB_v2
	 * Signature: (JJJJJJFIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1batchNorm_1deltaAB_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jfloat, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_layerNorm_deltaA_v2
	 * Signature: (JJJJJFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1layerNorm_1deltaA_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    field_layerNorm_deltaAB_v2
	 * Signature: (JJJJJJFIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_field_1layerNorm_1deltaAB_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jfloat, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_linear
	 * Signature: (JJFFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1linear
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_linear_dual
	 * Signature: (JJJFFFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1linear_1dual
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_quadratic
	 * Signature: (JJFFFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1quadratic
	(JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_quadratic_dual
	 * Signature: (JJJFFFFFFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1quadratic_1dual
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_linear_quadratic
	 * Signature: (JJJFFFFFIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1linear_1quadratic
	(JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_max
	 * Signature: (JJIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1max
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_min
	 * Signature: (JJIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1min
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_max_indexed
	 * Signature: (JJIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1max_1indexed
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_min_indexed
	 * Signature: (JJIIJJJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1min_1indexed
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_softmax
	 * Signature: (JJJJIIJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1softmax
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_softmaxCrossEntropy_stage1
	 * Signature: (JJJIIJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1softmaxCrossEntropy_1stage1
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_layernorm_deltaXp_v1
	 * Signature: (JJJJJJFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1layernorm_1deltaXp_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_layernorm_affined_deltaXp_v1
	 * Signature: (JJJJJJFJJIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1layernorm_1affined_1deltaXp_1v1
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jlong, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_layernorm_deltaXp_v2
	 * Signature: (JJJJJJFIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1layernorm_1deltaXp_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jfloat, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_reduce
	 * Method:    row_layernorm_affined_deltaXp_v2
	 * Signature: (JJJJJJFJIIJJIII)I
	 */
	JNIEXPORT jint JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1reduce_row_1layernorm_1affined_1deltaXp_1v2
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jfloat, jlong, jint, jint, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
